import Head from 'next/head'
import { lazy } from 'react'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar'
import Hero from '@/components/Herosection/Hero'
import About from '@/components/About/About'
// const Navbar = lazy(() => import('@/components/Navbar/Navbar'))
// const Hero = lazy(() => import('@/components/Herosection/Hero'))
// const About = lazy(() => import('@/components/About/About'));
// const WhatIDo = lazy(() => import('@/components/WhatIDo/WhatIDo'))
// const Skills = lazy(() => import('@/components/Skills/Skills'))
import WhatIDo from '@/components/WhatIDo/WhatIDo'
import Skills from '@/components/Skills/Skills'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Tushar Kumar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@700&family=Mulish&display=swap" rel="stylesheet" />
      </Head>
      <main >
        <div className='App'>
          <Navbar />
          <br />
          <br />
          <br />
          <br />
          <Hero />
          <About />
          <WhatIDo />
          <Skills />
        </div>
      </main>
    </>
  )
}
